package tahery.meslage.epicture.model

data class ImageModel( var id : String?,
                       var title : String?,
                       var desecription : String?,
                       var datetime : Int,
                       var type : String?,
                       var animated : Boolean,
                       var width : Int,
                       var height : Int,
                       var size : Int,
                       var view : Int,
                       var bandwidth : Long,
                       var vote : Int,
                       var section : String?,
                       var account_url : String?,
                       var account_id : Int,
                       var is_ad : Boolean,
                       var in_most_viral : Boolean,
                       var has_sound : Boolean,
                       var tags : List<String>,
                       var ad_type : Int,
                       var ad_url : String?,
                       var edited : String?,
                       var in_gallery : Boolean,
                       var deletehash : String?,
                       var name : String?,
                       var link : String?,
                       var mp4_size :Int,
                       var mp4: String?,
                       var hls : String?
                       )